use anyhow::Context;
use aya::{
    maps::HashMap,
    programs::{CgroupAttachMode,
        CgroupSockAddr,
        cgroup_skb, 
        Xdp, 
        XdpFlags},
    include_bytes_aligned,
};
use aya_log::EbpfLogger;
use clap::Parser;
use log::{info, warn};
use std::{fs::File, net::Ipv4Addr};
use tokio::signal;

#[derive(Debug, Parser)]
struct Opt {
    #[clap(short, long, default_value = "/sys/fs/cgroup")]
    cgroup_path: String,
    #[clap(short, long, default_value = "eth0")] // FIX LATER This should apply automatically to EVERY interface (except for maybe loopback?)
    iface: String,
}

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let opt = Opt::parse();

    env_logger::init();

    // This will include your eBPF object file as raw bytes at compile-time and load it at
    // runtime. The path is generated by the build script.
    let mut bpf = aya::Ebpf::load(include_bytes_aligned!(concat!(
        env!("OUT_DIR"),
        "/firewhal-kernel"
    )))?;
    if let Err(e) = EbpfLogger::init(&mut bpf) {
        warn!("failed to initialize eBPF logger: {e}");
    }

    // ** NEED TO ADD IPv6 Programs later
    // INGRESS PROGRAMS

    // --- Attach XDP Program ---
    let xdp_prog: &mut Xdp = bpf.program_mut("firewhal_xdp").unwrap().try_into()?;
    xdp_prog.load()?;
    xdp_prog
        .attach(&opt.iface, XdpFlags::default())
        .context("failed to attach XDP program")?;
    info!("Attached XDP filter program to interface {}.", opt.iface);

    // --- Attach Ingress recvmsg4 Program ---
    // This program should be optional to the user as it adds additional overhead that may be unnecessary to their needs
    let ingress_recvmsg4_prog: &mut CgroupSockAddr = bpf.program_mut("firewhal_ingress_recvmsg4").unwrap().try_into()?;
    ingress_recvmsg4_prog.load()?;
    let cgroup = File::open(&opt.cgroup_path)?;
    ingress_recvmsg4_prog
        .attach(cgroup, CgroupAttachMode::Single)
        .context("failed to attach XDP program")?;
    info!("Attached XDP filter program to interface {}.", opt.iface);


    //EGRESS PROGRAMS 

    // --- Attach Egress connect4 Program ---
    let egress_connect4_prog: &mut CgroupSockAddr =
        bpf.program_mut("firewhal_egress_connect4").unwrap().try_into()?;
    egress_connect4_prog.load()?;
    // We need to re-open the cgroup file to get a new, independent file descriptor.
    let cgroup = File::open(&opt.cgroup_path)?;
    egress_connect4_prog
        .attach(cgroup, CgroupAttachMode::Single)
        .context("failed to attach egress program")?;
    info!("Attached cgroup egress filter program.");


    // --- Attach Egress bind4 Program ---
    let egress_bind4_prog: &mut CgroupSockAddr =
        bpf.program_mut("firewhal_egress_bind4").unwrap().try_into()?;
    egress_bind4_prog.load()?;
    // We need to re-open the cgroup file to get a new, independent file descriptor.
    let cgroup = File::open(&opt.cgroup_path)?;
    egress_bind4_prog
        .attach(cgroup, CgroupAttachMode::Single)
        .context("failed to attach egress program")?;
    info!("Attached cgroup egress filter program.");


    // --- Attach Egress sendmsg4 Program ---
    let egress_sendmsg4_prog: &mut CgroupSockAddr =
        bpf.program_mut("firewhal_egress_sendmsg4").unwrap().try_into()?;
    egress_sendmsg4_prog.load()?;
    // We need to re-open the cgroup file to get a new, independent file descriptor.
    let cgroup = File::open(&opt.cgroup_path)?;
    egress_sendmsg4_prog
        .attach(cgroup, CgroupAttachMode::Single)
        .context("failed to attach egress program")?;
    info!("Attached cgroup egress filter program.");

    // --- Configure Maps ---
    // Configure ingress port blocklist
    // *** FIX THIS
    // let mut port_blocklist: HashMap<_, u16, u8> =
    //     HashMap::try_from(bpf.map_mut("PORT_BLOCKLIST").unwrap())?;
    // let blocked_port = 8080u16;
    // port_blocklist.insert(blocked_port, 1, 0)?;
    // info!("[Rule] Blocking incoming TCP/UDP traffic to port {}", blocked_port);

    // Configure ingress ICMP block
    let mut icmp_block: HashMap<_, u8, u8> =
        HashMap::try_from(bpf.map_mut("ICMP_BLOCK_ENABLED").unwrap())?;
    icmp_block.insert(1, 1, 0)?;
    info!("[Rule] Blocking all incoming ICMP (ping) traffic via XDP.");

    // Configure egress IP blocklist
    let mut blocklist: HashMap<_, u32, u32> =
        HashMap::try_from(bpf.map_mut("BLOCKLIST").unwrap())?;
    let block_addr: u32 = Ipv4Addr::new(1, 1, 1, 1).into();
    blocklist.insert(block_addr, 0, 0)?;
    info!("[Rule] Blocking outgoing connections to 1.1.1.1");

    info!("Waiting for Ctrl-C...");
    signal::ctrl_c().await?;
    info!("Exiting...");

    Ok(())
}